cilium: clean up bpf_network includes
[ upstream commit 99070f653924db027191d4eb4b2ca4065f1bbae2 ]

[ Backporter's notes: Also had to clean up "l3.h" to avoid:
                      error: use of undeclared identifier 'NODE_MAC'" ]

bpf_network is pulling in unneeded headers resulting in compile errors
on older kernels. Use the linux/*.h headers for the handful of types
that the program actually uses.

Signed-off-by: John Fastabend <john.fastabend@gmail.com>